import type { NextPage } from 'next';
import Head from 'next/head';
import SignIn from '../components/SignIn/SignIn';
import { useSession } from 'next-auth/react';
import Link from 'next/link';

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Create an account to get startet</h1>
      <SignIn />

      {session && (
        <h2>
          <Link href="/dashboard">Go to the Dashboard</Link>
        </h2>
      )}
    </div>
  );
};

export default Home;
